name: Build and Publish MSLearn Catalog API library

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      working-directory: ./src
      run: dotnet restore
    - name: Build
      working-directory: ./src
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./src
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      working-directory: ./src
      run: dotnet pack MSLearnCatalogAPI.csproj --output nuget-packages --configuration Release
    - name: Push to NuGet
      working-directory: ./src
      run: dotnet nuget push nuget-packages/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
